### ISSUE TITLE
ELIMINACIÓN DE MENÚS Y/O ELIMINACIÓN DE PERFILES 

### ISSUE THREAD

**Issue by fabianLeon** [udistrital/configuracion_cliente#1]
No se puede eliminar un menú, y la alerta no informa acerca de porque no se deja eliminar el menú.

**Comment by fabianLeon** [comment]
El mensaje alert dice "No se puede eliminar el menu"

**Comment by jsreyes** [comment]
Se realizan los commits respectivos al ajuste de la función borrar(), se cambian las alertas por sweetalerts2 y además se realiza configuración de validaciones, para el proceso de Desvinculación de los menús asociados a los perfiles.
