### ISSUE TITLE
Migración de datos del esquema MNTAC  a BD en AWS

### ISSUE THREAD

**Issue by a52290451** [udistrital/configuracion_cliente#10]
Registrar la migración de datos realizada desde el esquema MNTAC a entorno de BD de pruebas creado en AWS.

**Criterio de aceptación**

- [ ] Documentación que soporte la migración realizada.

**Comment by AlejaB18** [comment]
![image](https://user-images.githubusercontent.com/85303858/145125477-e3c9ae8d-ae8d-4231-bbd3-739aaa0c8a77.png)

**Comment by AlejaB18** [comment]
[Amazon RDS for Oracle.pdf](https://github.com/udistrital/configuracion_cliente/files/7672363/Amazon.RDS.for.Oracle.pdf)

**Comment by AlejaB18** [comment]
[report-Amazon RDS for PostgreSQL-2021-12-01-01-45.csv](https://github.com/udistrital/configuracion_cliente/files/7672367/report-Amazon.RDS.for.PostgreSQL-2021-12-01-01-45.csv)

**Comment by a52290451** [comment]
Se valida migración realizada.
