### ISSUE TITLE
Modificación de Procedimientos y Funciones - MNTAC

### ISSUE THREAD

**Issue by a52290451** [udistrital/configuracion_cliente#4]
Modificar los procedimientos y funciones a las que haya lugar en el esquema MNTAC para el proceso de migración.

**Criterios de aceptación**

- [x] Documentación y scripts que evidencien las modificaciones realizadas a nivel de procedimientos.
- [x] - [ ] Documentación y scripts que evidencien las modificaciones realizadas a nivel de funciones.

**Comment by AlejaB18** [comment]
[ProcedureSCT.txt](https://github.com/udistrital/configuracion_cliente/files/7509488/ProcedureSCT.txt)

**Comment by AlejaB18** [comment]
[functionSCT.txt](https://github.com/udistrital/configuracion_cliente/files/7509496/functionSCT.txt)
