### ISSUE TITLE
Pruebas funcionales en BD local y entorno de pruebas - MNTAC

### ISSUE THREAD

**Issue by a52290451** [udistrital/configuracion_cliente#5]
Realizar pruebas funcionales en Bases de Datos locales y en ambiente de pruebas, posterior a la terminación del proceso de migración del esquema MNTAC.

**Criterios de aceptación**

- [x] Documentación o evidencia de pruebas funcionales realizadas.

**Comment by AlejaB18** [comment]
[report-Amazon Aurora (PostgreSQL compatible)-2021-09-28-10-55.xlsx](https://github.com/udistrital/configuracion_cliente/files/7671600/report-Amazon.Aurora.PostgreSQL.compatible.-2021-09-28-10-55.xlsx)

Se realiza validación de todos los eventos que generó la herramienta de SCT respecto a ejercicio de migración local para documentación y diseño de solución
