### ISSUE TITLE
Migración registros - MNTAC

### ISSUE THREAD

**Issue by a52290451** [udistrital/configuracion_cliente#6]
Ejecutar la migración de registros provenientes del esquema MNTAC, a fin de completar el ciclo de migración de la BD ORACLE académica a AURORA postgres en su primer alcance.

**Criterios de aceptación**

- [x] Evidencia de migración de registros realizada.

**Comment by AlejaB18** [comment]
No fue posible hacer migración de registros a nivel local, ya que mi máquina no permitió realizar el cargue de la data por capacidad, se decide dar continuidad a la migración a bd de pruebas y trabajar en conocimiento DMS como herramienta de migración de data a bd de prueba postgres RDS
