### ISSUE TITLE
Validación y ajustes - Sprint 2

### ISSUE THREAD

**Issue by a52290451** [udistrital/configuracion_cliente#7]
Presentar los avances realizados en cuanto a las tareas contempladas para el segundo sprint relacionado con la Migración de Datos a los interesados (Usuarios DBAs) para su validación y realizar los ajustes necesarios.

**Criterio de aceptación**

- [x] Acta de entregables firmada por las partes involucradas, asociada al segundo sprint.

**Comment by AlejaB18** [comment]
Se realiza reunión de presentación de contexto sobre el plan de trabajo respecto a la migración de MNTAC, incluyendo lo realizado en el primer sprint y el detalle de las modificaciones de scripts y validación de eventos notificados por SCT. En la reunión se aprobó el avance del proyecto, se notificó la no migración de data a local y se recibió aprobación para dar continuidad con el plan de trabajo. Se deja constancia mediante grabación de la reunión a acceder en el siguiente link:
https://drive.google.com/file/d/1xAsGV6ewCY9ckyHd4lZcB72ERcYMAhPG/view?usp=sharing
