### ISSUE TITLE
Validación y análisis de datos migrados

### ISSUE THREAD

**Issue by a52290451** [udistrital/configuracion_cliente#8]
De acuerdo a la migración realizada en la base de datos creada en AWS, se requiere adelantar el proceso de validación y análisis de la migración. Se debe corroborar que toda la data migrada, asociada al esquema MNTAC, guardó su integridad en cuanto triggers, vistas, constrains y demás elementos asociados.

**Criterios de aceptación**

- [x] Documentación asociada al proceso de validación.

**Comment by AlejaB18** [comment]
[Estimacion esquemas.xlsx](https://github.com/udistrital/configuracion_cliente/files/7763075/Estimacion.esquemas.xlsx)

**Comment by AlejaB18** [comment]
Para control de avance sobre los esquemas leídos por la herramienta SCT y migrados a la base de datos academicapgmigracion.udistritaloas.edu.co Postgres RDS en Amazon, se relaciona el siguiente archivo de actualización constante hasta el logro de validación y corrección necesaria para los 49 esquemas listados en el archivo previamente adjunto a los comentarios del presente issue y que será accedido mediante el siguiente [enlace](https://docs.google.com/spreadsheets/d/1CqSxXwwjmPF3xOJTI-De2KYnsu6W3g7q/edit?usp=sharing&ouid=110895415307001295158&rtpof=true&sd=true)
